// web/src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { auth } from '$lib/stores/auth';
  import { locale, t } from '$lib/stores/locale';
  import Card from '$lib/components/Card.svelte';
  import Input from '$lib/components/Input.svelte';
  import Button from '$lib/components/Button.svelte';

  let username = '';
  let password = '';
  let loading = false;
  let error = '';

  async function submit() {
    loading = true;
    error = '';
    try {
      await auth.login(username, password);
      goto('/');
    } catch (e: unknown) {
      const err = e as { message?: string };
      error = err.message || t($locale, 'login.error');
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen flex items-center justify-center px-4">
  <div class="w-full max-w-md">
    <Card strip padding="lg">
      <div class="mb-6">
        <h1 class="text-xl font-semibold" style="color: var(--text)">
          {t($locale, 'login.title')}
        </h1>
        <p class="mt-1 text-sm" style="color: var(--text-muted)">
          {t($locale, 'app.subtitle')}
        </p>
      </div>

      <form on:submit|preventDefault={submit} class="space-y-4">
        <Input
          bind:value={username}
          label={t($locale, 'login.username')}
          autocomplete="username"
          required
        />
        <Input
          bind:value={password}
          type="password"
          label={t($locale, 'login.password')}
          autocomplete="current-password"
          required
        />
        {#if error}
          <p class="text-sm" style="color: var(--danger)">{error}</p>
        {/if}
        <Button type="submit" fullWidth {loading}>{t($locale, 'login.submit')}</Button>
      </form>
    </Card>
  </div>
</div>

// web/src/pages/Login.tsx
import { useState } from 'react'
import { login } from '../lib/api'

export default function LoginPage({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login(email, password)
      onLogin()
    } catch {
      setError('Invalid credentials')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div
      className="min-h-screen flex items-center justify-center"
      style={{ background: 'var(--bg-primary)' }}
    >
      <div
        className="w-full max-w-sm rounded-2xl p-8 border"
        style={{ background: 'var(--bg-secondary)', borderColor: 'var(--border)' }}
      >
        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold tracking-tight">
            <span style={{ color: 'var(--accent)' }}>mq</span>Connector
          </h1>
          <p className="text-sm mt-2" style={{ color: 'var(--text-secondary)' }}>
            Sign in to your admin account
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
              Email
            </label>
            <input
              type="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
              className="w-full px-3 py-2.5 rounded-lg text-sm outline-none transition-all focus:ring-2"
              style={{
                background: 'var(--bg-primary)',
                border: '1px solid var(--border)',
                color: 'var(--text-primary)',
                '--tw-ring-color': 'var(--accent)',
              } as React.CSSProperties}
              placeholder="admin@example.com"
              required
            />
          </div>

          <div>
            <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>
              Password
            </label>
            <input
              type="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
              className="w-full px-3 py-2.5 rounded-lg text-sm outline-none transition-all focus:ring-2"
              style={{
                background: 'var(--bg-primary)',
                border: '1px solid var(--border)',
                color: 'var(--text-primary)',
                '--tw-ring-color': 'var(--accent)',
              } as React.CSSProperties}
              placeholder="••••••••"
              required
            />
          </div>

          {error && (
            <p className="text-sm text-center" style={{ color: 'var(--red)' }}>{error}</p>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2.5 rounded-lg text-sm font-medium transition-all disabled:opacity-50"
            style={{ background: 'var(--accent)', color: '#fff' }}
          >
            {loading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>
      </div>
    </div>
  )
}
